name: ystilos
favicon: null
layout_spectrum: 0.51595
typography_spectrum: 0.49497
title: ILLUSTRATOR /  DESIGNER
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#edd7a8'
    - '#30757c'
    - '#ea4d3a'
    - '#aeac59'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
