name: ystilos
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49497
title: ILLUSTRATOR /  DESIGNER
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98c5c0'
    - '#306761'
    - '#313639'
    - '#dceeee'
    - '#765455'
  brandStrength: 0.3125
  lightness: 0.9231778928078711
  saturation: 1
  rhythmicContrast: 0.05161374108865857
purpose: []
