typography_spectrum: 0.49497
color:
  brandColors:
    - '#000000'
    - '#edd7a8'
    - '#30757c'
    - '#ea4d3a'
    - '#aeac59'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24955
analytics:
  google: null
  facebook: null
  twitter: null
name: ystilos
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Baobap
    id: a948ab28-4efa-4be3-9125-d2393a9079ab
    type: content
favicon: null
title: ILLUSTRATOR /  DESIGNER
purpose: []
